mendix/widgets-tools

- .github/workflows/ShaCheck.yml
- packages/pluggable-widgets-tools/CHANGELOG.md
- packages/pluggable-widgets-tools/bin/mx-scripts.js
- packages/pluggable-widgets-tools/package-lock.json
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/association.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/containment.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/index.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/list-association.ts
- packages/pluggable-widgets-tools/src/typings-generator/generatePreviewTypes.ts
-   Compatible with: MX 9️⃣
_This is a recreation of https://github.com/mendix/widgets-resources/pull/1593 from the old repository._
For the sake of consistency between the Pluggable Widget API and the client, we have replaced the className preview property with class.
- Preview types generator
- Verify whether the preview type generator uses the right property name.
> [PAG-1317]: replace className with class in editorPreview

- scripts/release/createRelease.ts
The commit message for changelog updates in the release process was still using the "semantic" message format that was retired during the repo split.
> Fix the commit message for changelog updates when releasing a package

- packages/pluggable-widgets-tools/CHANGELOG.md
- packages/pluggable-widgets-tools/bin/mx-scripts.js
- packages/pluggable-widgets-tools/src/typings-generator/WidgetXml.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/index.spec.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/inputs/expression.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/expression.ts
- packages/pluggable-widgets-tools/src/typings-generator/generateClientTypes.ts
- packages/pluggable-widgets-tools/src/typings-generator/helpers.ts
Add support for expression return type to refer to another property and generate its types.
- Update case 'expression' from `toClientPropType` fn to generate types based on the existence of the attribute `assignableTo` on the returnType property.
> [WTF-1176]: return type depending on another property

- packages/pluggable-widgets-tools/CHANGELOG.md
- packages/pluggable-widgets-tools/test-config/transform.js
Right now during unit test run babel generate lot of warnings, this config update should prevent them
```
column-chart-web:test: Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
column-chart-web:test: The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
column-chart-web:test: 	["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
column-chart-web:test: to the "plugins" section of your …
```
> Update babel-jest config to prevent noisy warnings

- packages/generator-widget/package.json
- packages/pluggable-widgets-tools/package.json
This PR bump the pluggable-widgets-tools and generator-widget version to `9.20.0`
> [WTF-1321]: Bump version to 9.20.0 for pwt and gw

- packages/pluggable-widgets-tools/package.json
- packages/pluggable-widgets-tools/src/typings-generator/WidgetXml.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/index.spec.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/inputs/selection.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/selection.ts
- packages/pluggable-widgets-tools/src/typings-generator/generate.ts
- packages/pluggable-widgets-tools/src/typings-generator/generateClientTypes.ts
- packages/pluggable-widgets-tools/src/typings-generator/generatePreviewTypes.ts
-   Compatible with: MX 9️⃣
-   Did you update version and changelog? ✅❌
Add support to the typings generator for the new `selection` property, which is added as a beta feature in Mendix 9.23. Since the feature is still in beta, we are omitting it from the changelog for now.
Depending on the configuration of the `selection` property, the typings generator will now emit:
- A client prop of (union) type `SelectionSingleValue` and/or `SelectionMultiValue`. Selection type `None` and/or a linked data source with `required="false"` results in an optional prop.
- A preview prop of …
> [WTF-1370] Add support for selection property (beta) to the typings generator

- package.json
- packages/pluggable-widgets-tools/CHANGELOG.md
- packages/pluggable-widgets-tools/package-lock.json
- packages/pluggable-widgets-tools/package.json
- 
Fix the missing dist folder introduced on the pluggable-widgets-tools 9.23.0 release.
Replace the build script by prepare in the pluggable-widgets-tools.
The prepare script is necessary to trigger a build when installing the pluggable-widgets-tools.
Make sure that the dist folder is generated after a npm install is called in the root folder or in the `packages/pluggable-widgets-tools` folder.
> [WTF-1432]: Missing dist folder in pwt 9.23.0

- packages/pluggable-widgets-tools/CHANGELOG.md
- packages/pluggable-widgets-tools/package-lock.json
- packages/pluggable-widgets-tools/package.json
- packages/pluggable-widgets-tools/test-config/jest.config.js
- packages/pluggable-widgets-tools/test-config/jest.native.config.js
-   [x] Refactor
Adjust Jest configuration to also work for widget tests.
Change Jest testEnvironment to jsdom.
This MR also changes the ts-jest config to disable type checkings to improve CI performance.
It was previously taking +3 hours to finish running PWT Script Tests.
> [WTF-1433]: Change jest testEnvironment from node to jsdom on jest.native.config and jest.config.js

- packages/pluggable-widgets-tools/CHANGELOG.md
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/association.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/datasource.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/expression.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/list-association.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/selection.ts
- packages/pluggable-widgets-tools/src/typings-generator/generatePreviewTypes.ts
-   Compatible with: MX 9️⃣
This PR adds a caption field to the DataSource so that custom widgets have access to DataSource caption as is used in the Page Explorer when generating previews for the page editor.
This feature will be added in the 9.24 version.
Updated the typings generator for GetPreview
Widgets should be able to understand the DataSource caption when generating a preview for the page editor
> [PAG-2016] Add the DataSource caption property

- packages/generator-widget/CHANGELOG.md
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_native.json-js-unit.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_native.json-js.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_native.json-ts-unit.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_native.json-ts.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-js-e2e.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-js-unit-e2e.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-js-unit.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-js.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-ts-e2e.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-ts-unit-e2e.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-ts-unit.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-ts.json
- packages/generator-widget/generators/app/templates/packages/package_native.json.ejs
- packages/generator-widget/generators/app/templates/packages/package_web.json.ejs
- packages/generator-widget/package-lock.json
- packages/generator-widget/package.json
- packages/pluggable-widgets-tools/CHANGELOG.md
- packages/pluggable-widgets-tools/package-lock.json
- packages/pluggable-widgets-tools/package.json
-   Contains unit tests ✅ 
-   Contains breaking changes ✅ 
-   Compatible with: MX 7️⃣, 8️⃣, 9️⃣ ,🔟 
To update the Mendix typings from v9.24.2965 to v10.0.9976
In this PR we are bumping the Mendix package to v10.0.9976 in the pluggable-widgets-tools package and also bumping the generator-widget package.json templates to include the Mendix 10
> [WTF-1531]: Bump the mendix typings from v9.24.2965 to v10.0.9976

- packages/pluggable-widgets-tools/CHANGELOG.md
- packages/pluggable-widgets-tools/configs/rollup-plugin-assets.js
-   Compatible with: MX 7️⃣, 8️⃣, 9️⃣, 🔟
To fix a bug in the rollup-plugin-assets.js causing assets url to not return in Unix format, which then breaks on Windows.
> [WTF-1602] Fix rollup windows exports must be in unix format

- packages/pluggable-widgets-tools/package.json
- packages/pluggable-widgets-tools/utils/migration.js
Fix the misaligned versions for `react`, `react-dom`, `react-native` packages and their corresponding `@types` packages during migration.
-   Compatible with:
-   Did you update version and changelog?  ❌
The migration script creates resolutions and overrides for three packages in an incorrect way. This PR fixes the issue by aligning the versions of those packages in the migration script.
Some hard coded values are adjusted and extracted into constants to be the same everywhere they are relavant.
An example widget should be upgraded using the standard procedure. Another PR in docs repository is on the way to clearly state this standard procedure of upgrade.
> [WTF-1735]: Fix PWT resolution/override versions

- README.md
- packages/generator-widget/CHANGELOG.md
- packages/generator-widget/README.md
- packages/generator-widget/bin.js
- packages/generator-widget/generators/app/lib/text.js
- packages/generator-widget/package-lock.json
- packages/generator-widget/package.json
- 
This PR introduces a npx command line to quickly scaffold a widget without the need to install Yeoman Generator and the @medix/generator-widget package.
Currently, to generate a widget you need to first install the `yeoman` package globally together with the `@medix/widget-generator`.
With this change you can just call the @medix/widget-generator package directly from the command line using npx.
Example:
`npx @mendix/generator-widget MyWidgetName`
- Is it still possible to generate a widget inside an empty folder?
- Widget can be generated when the provided name has spaces? Ex: `npx …
> [WTF-1751] Improve Widget Generator DevX by introducing npx command line

- packages/pluggable-widgets-tools/CHANGELOG.md
- packages/pluggable-widgets-tools/package-lock.json
- packages/pluggable-widgets-tools/package.json
-   Contains unit tests ❌ 
-   Compatible with: MX 7️⃣, 8️⃣, 9️⃣ ,🔟 
To update the Mendix typings from v10.5.216275 to v10.7.26214
In this PR we are bumping the Mendix package to  v10.7.26214 in the pluggable-widgets-tools package
> [WTF-1757] Bump the mendix typings from v10.5.216275 to v10.7.26214

- packages/generator-widget/CHANGELOG.md
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_native.json-js-unit.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_native.json-js.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_native.json-ts-unit.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_native.json-ts.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-js-e2e.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-js-unit-e2e.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-js-unit.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-js.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-ts-e2e.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-ts-unit-e2e.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-ts-unit.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-ts.json
- packages/generator-widget/generators/app/templates/packages/package_native.json.ejs
- packages/generator-widget/generators/app/templates/packages/package_web.json.ejs
- packages/generator-widget/package-lock.json
- packages/generator-widget/package.json
- packages/pluggable-widgets-tools/CHANGELOG.md
- packages/pluggable-widgets-tools/configs/rollup.config.js
- packages/pluggable-widgets-tools/package-lock.json
- packages/pluggable-widgets-tools/package.json
-   Compatible with: MX 7️⃣, 8️⃣, 9️⃣, 🔟
-   [x] Refactor
This PR fixes an issue with rollup treating "module directives" warning as an error which was causing bundling to fail.
_..._
- The warning `MODULE_LEVEL_DIRECTIVE` should return to not kill the bundle process and pollute the terminal since it should be a common warning from now on as more libraries implement react directives.
- The warning message style has been changed to use the standard `warn` function from Rollup since its output on the terminal is better formatted. Example below:
Before:
After:
- That importing libraries like `ag-grid-react`, …
> [WTF-1780]: module level directive warnings should not cause bundling to fail

- packages/pluggable-widgets-tools/CHANGELOG.md
- packages/pluggable-widgets-tools/configs/rollup.config.js
-   Contains unit tests  ❌
-   Did you update version and changelog? ❌
Sometimes when running the pluggable widget tools script for release or build a widget, the rollup doesn’t finish the process. That happens in the editorConfig step.
To resolve that for now I have followed one suggestion from the rollup repository PR to force close the process because we’re still using rollup v3 in the pluggable widget tools. 
That was fixed in v4, it was created one new parameter to pass to rollup to force exit. If so, then this fix can be removed and starts to use the new parameter mentioned above. …
> [WC-2383] Force close rollup process hanging

- packages/pluggable-widgets-tools/CHANGELOG.md
- packages/pluggable-widgets-tools/configs/rollup.config.js
- packages/pluggable-widgets-tools/configs/rollup.config.native.js
- packages/pluggable-widgets-tools/configs/shared.js
- packages/pluggable-widgets-tools/package-lock.json
- packages/pluggable-widgets-tools/package.json
-   Compatible with: MX 7️⃣, 8️⃣, 9️⃣, 10
This PR fixes sourceMap warnings causing the bundling to fail.
Build a widget that uses an external library that supports react directives.
Examples: `react-toastify`
The bundling process should not throw an error
> [WTF-1855] Fix rollup hanging while bundling files with react directive and sourcemaps

- packages/generator-widget/CHANGELOG.md
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_native.json-js-unit.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_native.json-js.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_native.json-ts-unit.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_native.json-ts.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-js-e2e.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-js-unit-e2e.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-js-unit.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-js.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-ts-e2e.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-ts-unit-e2e.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-ts-unit.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-ts.json
- packages/generator-widget/generators/app/templates/packages/package_native.json.ejs
- packages/generator-widget/generators/app/templates/packages/package_web.json.ejs
- packages/pluggable-widgets-tools/package-lock.json
-   Contains unit tests ✅ 
-   Compatible with: MX 🔟
-   Did you update version and changelog? ✅ 
-   [x] Other (describe)
The purpose of the changes is to fix the compilation error due to a version mismatch among the dependencies. 
The Yeoman Generator for scaffolding a pluggable widget has been adjusted to include `@types/react` package with `18.2.79`. Related unit tests are also adjusted in accordance with the changes.
> [WTF-1922]: Fix react and @types/react package mismatch in PWT

- packages/pluggable-widgets-tools/CHANGELOG.md
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/association.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/atribute-linked-action.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/containment.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/datasource.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/expression.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/file.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/icon.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/index.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/list-action.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/list-association.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/list-attribute-refset.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/list-files.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/list-image.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/selection.ts
- packages/pluggable-widgets-tools/src/typings-generator/generatePreviewTypes.ts
-   Compatible with: MX 10
-   [X ] Feature
This PR will introduce a new parameter to the generated pluggable widgets that will allow users to change the rendering according to which mode the canvas is currently in.
Add a field to the generator for pluggable widget preview properties that can take one of 3 values, namely "xray", "design" and "structure"
Check that generated widget preview properties has the "renderMode: "xray", "design", "structure";" property added
> [PAG-2309] Add support for render modes on pluggable widgets

- packages/pluggable-widgets-tools/src/typings-generator/__tests__/index.spec.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/inputs/non-linked-list-attribute-refset.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/non-linked-list-attribute-refset.ts
‼️ ## NOTE: This PR is supposed to be merged after the 10.13 release with the new typings package.
Add unit tests for non-linked attribute property with reference sets.
-   Contains unit tests ✅ 
-   Compatible with: MX 🔟
-   Did you update version and changelog? ❌
-   [x] Other (describe)
This PR adds unit tests for typings generation in PWT the recently implemented reference sets with attribute property story.
> [WTF-1883]: Support reference sets for non-linked attribute property

- packages/generator-widget/CHANGELOG.md
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_native.json-js-unit.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_native.json-js.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_native.json-ts-unit.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_native.json-ts.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-js-e2e.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-js-unit-e2e.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-js-unit.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-js.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-ts-e2e.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-ts-unit-e2e.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-ts-unit.json
- packages/generator-widget/generators/app/templates/packages/__tests__/outputs/package_web.json-ts.json
- packages/generator-widget/generators/app/templates/packages/package_native.json.ejs
- packages/generator-widget/generators/app/templates/packages/package_web.json.ejs
- packages/generator-widget/package-lock.json
- packages/generator-widget/package.json
- packages/pluggable-widgets-tools/CHANGELOG.md
- packages/pluggable-widgets-tools/package-lock.json
- packages/pluggable-widgets-tools/package.json
- packages/pluggable-widgets-tools/src/typings-generator/WidgetXml.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/index.spec.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/inputs/datasource.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/inputs/metadata-attribute.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/metadata-attribute.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/non-linked-list-attribute-refset.ts
- packages/pluggable-widgets-tools/src/typings-generator/generate.ts
- packages/pluggable-widgets-tools/src/typings-generator/generateClientTypes.ts
- packages/pluggable-widgets-tools/src/typings-generator/generatePreviewTypes.ts
-   Compatible with: MX 🔟 (After next release of typings package)
-   Did you update version and changelog?  ✅
To lay the groundwork for offering cross-widget filtering and sorting of data sources. Enabling widget developers to build reusable and flexible filter controls.
This PR introduces the `AttributeMetaDataProperty` type. 
That an attribute with the `isMetaData=true` flag results in a `AttributeMetaData` type.
> [WTF-1986] Generate types for metadata attribute properties

- packages/pluggable-widgets-tools/CHANGELOG.md
- packages/pluggable-widgets-tools/package-lock.json
- packages/pluggable-widgets-tools/package.json
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/index.spec.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/inputs/metadata-association.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/inputs/metadata-attribute.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/metadata-association.ts
- packages/pluggable-widgets-tools/src/typings-generator/generate.ts
- packages/pluggable-widgets-tools/src/typings-generator/generateClientTypes.ts
-   Contains unit tests ✅ 
-   Compatible with: MX 🔟
-   Did you update version and changelog? ❌ (This will be done after the release.)
This PR introduces types generation for `AssociationMetaData`.
Client types generator is adjusted to incorporate the recently developed PW API of flexible filtering over associations.
Testing should include, creating a `AssociationMetaData` property in the Widget Definition XML and verifying (after building the widget to trigger the generator) the resulting widget property TypeScript types.
> [WTF-1967]: Generate widget property types for metadata associations

- packages/pluggable-widgets-tools/CHANGELOG.md
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/association.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/atribute-linked-action.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/containment.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/datasource.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/expression.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/file.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/icon.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/index.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/list-action.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/list-association.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/list-attribute-refset.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/list-files.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/list-image.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/metadata-association.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/metadata-attribute.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/non-linked-list-attribute-refset.ts
- packages/pluggable-widgets-tools/src/typings-generator/__tests__/outputs/selection.ts
- packages/pluggable-widgets-tools/src/typings-generator/generatePreviewTypes.ts
-   Compatible with: MX 9️⃣
-   Did you update version and changelog? ✅ ❌
-   [ x ] Bug fix
-   [ x ] Feature
PAG added the translate function to the preview props, this adds the appropriate typing. We also noticed that the type for the mode (design, structure, x-ray) was made nullable on accident.
Generated types for the preview props.
The updated unit tests should be sufficient.
> [PAG-2505] Update generatePreviewTypes to add translate function

- packages/pluggable-widgets-tools/CHANGELOG.md
- packages/pluggable-widgets-tools/README.md
- packages/pluggable-widgets-tools/docs/rollup3-guide.md
This change fixes the formatting of the changelog to comply with the changelog grammar.
> Comply with changelog grammar

- .github/workflows/TestPWTCommands.yml
- .github/workflows/UnitTests.yml
This change cherry-picks the fix by Marco that updates the cache hash for the actions provided by Github.
> Update actions/cache to latest version

- packages/pluggable-widgets-tools/CHANGELOG.md
- packages/pluggable-widgets-tools/configs/rollup.config.mjs
- packages/pluggable-widgets-tools/configs/rollup.config.native.mjs
- packages/pluggable-widgets-tools/package-lock.json
- packages/pluggable-widgets-tools/package.json
-   Contains breaking changes  ❌
-   Did you update version and changelog?  ❌
-   [x] Other (describe)
Potentially fix some interesting build errors.
Update ts-node.
> [WC-2862]: fix import and bump ts-node

- packages/pluggable-widgets-tools/CHANGELOG.md
- packages/pluggable-widgets-tools/configs/rollup.config.mjs
- packages/pluggable-widgets-tools/package-lock.json
- packages/pluggable-widgets-tools/package.json
PR #117 addressed an import of a common js module that assumed it had a named export, which caused an error in some environments. It appears that this fix broke other widgets with custom configuration as the imported module does not have a default exported member.
This PR addresses both issues. It has been verified with the widgets that broke before and after 10.18.1.
> Fix import of commonJS module with no default

- .github/workflows/TestPWTCommands.yml
- .github/workflows/UnitTests.yml
- packages/command-tests/package.json
- packages/release-tools/package.json
- pnpm-lock.yaml
A few dependencies slipped through the cracks when migrating to pnpm: #132
> Add missing dependencies for release tooling
